import { db } from '../Configs/index.js';
import { CarListing } from '../Configs/schema.js';

const sampleCars = [
  {
    listingTitle: 'Tesla Model S Plaid',
    tagLine: 'The future of driving',
    originalPrice: '120000',
    category: 'Electric',
    sellingPrice: '99999',
    type: 'Electric',
    make: 'Tesla',
    condition: 'new',
    color: 'Black',
    year: '2024',
    driveType: 'AWD',
    model: 'Model S Plaid',
    fuelEfficiency: '120 MPGe',
    door: '4',
    engineSize: 'N/A',
    cylinder: '0',
    vin: '5YJ3E1EA8PF000001',
    offerType: 'Hot offer',
    listingDescription: 'Experience the pinnacle of electric performance with the Tesla Model S Plaid. Featuring 1,020 horsepower, 0-60 mph in 1.99 seconds, and a 396-mile range.',
    features: ['Sunroof', 'Leather Seats', 'Bluetooth', 'Backup Camera', 'Apple-CarPlay', 'Power Steering'],
    images: ['https://content.carlelo.com/uploads/blog_img/1710568288.webp'],
    userId: 'system_seed',
    userEmail: 'seed@example.com',
    userName: 'System Seed',
  },
  {
    listingTitle: 'BMW M3 Competition',
    tagLine: 'Pure driving pleasure',
    originalPrice: '85000',
    category: 'Sedan',
    sellingPrice: '74999',
    type: 'Petrol',
    make: 'BMW',
    condition: 'new',
    color: 'Blue',
    year: '2024',
    driveType: 'RWD',
    model: 'M3 Competition',
    fuelEfficiency: '19 MPG',
    door: '4',
    engineSize: '3.0L',
    cylinder: '6',
    vin: 'WBS8M9C00L0000002',
    offerType: 'Buy',
    listingDescription: 'The BMW M3 Competition delivers exhilarating performance with its 503-hp twin-turbo inline-6 engine. Premium interior with M Sport package.',
    features: ['Sunroof', 'Leather Seats', 'Bluetooth', 'Backup Camera', 'Brake Assist', 'Digital Odometer'],
    images: ['https://content.carlelo.com/uploads/blog_img/1710568288.webp'],
    userId: 'system_seed',
    userEmail: 'seed@example.com',
    userName: 'System Seed',
  },
  {
    listingTitle: 'Ford F-150 Raptor',
    tagLine: 'Built tough for any terrain',
    originalPrice: '78000',
    category: 'Truck',
    sellingPrice: '69999',
    type: 'Petrol',
    make: 'Ford',
    condition: 'new',
    color: 'Red',
    year: '2024',
    driveType: '4WD',
    model: 'F-150 Raptor',
    fuelEfficiency: '15 MPG',
    door: '4',
    engineSize: '3.5L',
    cylinder: '6',
    vin: '1FTFW1RG9LFA00003',
    offerType: 'Sell',
    listingDescription: 'Dominate any terrain with the Ford F-150 Raptor. Featuring Fox Racing Shox, 450-hp EcoBoost V6, and off-road ready suspension.',
    features: ['Bluetooth', 'Backup Camera', 'Power Steering', 'Rear Spoiler', 'Rain Sensing Wiper', 'Window-Electric'],
    images: ['https://content.carlelo.com/uploads/blog_img/1710568288.webp'],
    userId: 'system_seed',
    userEmail: 'seed@example.com',
    userName: 'System Seed',
  },
  {
    listingTitle: 'Audi e-tron GT',
    tagLine: 'Electric luxury redefined',
    originalPrice: '110000',
    category: 'Electric',
    sellingPrice: '94999',
    type: 'Electric',
    make: 'Audi',
    condition: 'new',
    color: 'Silver',
    year: '2024',
    driveType: 'AWD',
    model: 'e-tron GT',
    fuelEfficiency: '82 MPGe',
    door: '4',
    engineSize: 'N/A',
    cylinder: '0',
    vin: 'WAU2BHFZ9L0000004',
    offerType: 'Hot offer',
    listingDescription: 'The Audi e-tron GT combines stunning design with electric performance. 522 hp, 0-60 in 3.9 seconds, and a luxurious interior.',
    features: ['Sunroof', 'Leather Seats', 'Bluetooth', 'Backup Camera', 'Apple-CarPlay', 'Panoramic Moonroof'],
    images: ['https://content.carlelo.com/uploads/blog_img/1710568288.webp'],
    userId: 'system_seed',
    userEmail: 'seed@example.com',
    userName: 'System Seed',
  },
  {
    listingTitle: 'Toyota Land Cruiser',
    tagLine: 'Legendary off-road capability',
    originalPrice: '90000',
    category: 'SUV',
    sellingPrice: '84999',
    type: 'Hybrid',
    make: 'Toyota',
    condition: 'new',
    color: 'Gold',
    year: '2024',
    driveType: '4WD',
    model: 'Land Cruiser',
    fuelEfficiency: '23 MPG',
    door: '4',
    engineSize: '2.4L',
    cylinder: '4',
    vin: 'JTMCY7AJ0L0000005',
    offerType: 'Buy',
    listingDescription: 'The legendary Toyota Land Cruiser returns with a modern hybrid powertrain. Unmatched off-road capability meets everyday comfort.',
    features: ['Bluetooth', 'Backup Camera', 'Child Safety Locks', 'Heater', 'Power Steering', 'Vanity Mirror'],
    images: ['https://content.carlelo.com/uploads/blog_img/1710568288.webp'],
    userId: 'system_seed',
    userEmail: 'seed@example.com',
    userName: 'System Seed',
  },
  {
    listingTitle: 'Honda Civic Type R',
    tagLine: 'Track-ready performance',
    originalPrice: '45000',
    category: 'Hatchback',
    sellingPrice: '42999',
    type: 'Petrol',
    make: 'Honda',
    condition: 'new',
    color: 'Red',
    year: '2024',
    driveType: 'FWD',
    model: 'Civic Type R',
    fuelEfficiency: '24 MPG',
    door: '4',
    engineSize: '2.0L',
    cylinder: '4',
    vin: 'SHHFK8G74L0000006',
    offerType: 'Urgent',
    listingDescription: 'The Honda Civic Type R is the ultimate hot hatch. 315-hp turbocharged engine, manual transmission, and aggressive styling.',
    features: ['Bluetooth', 'Backup Camera', 'Digital Odometer', 'Rear Spoiler', 'Power Steering', 'Window-Electric'],
    images: ['https://content.carlelo.com/uploads/blog_img/1710568288.webp'],
    userId: 'system_seed',
    userEmail: 'seed@example.com',
    userName: 'System Seed',
  },
  {
    listingTitle: 'Mercedes-Benz G-Class',
    tagLine: 'Iconic luxury SUV',
    originalPrice: '150000',
    category: 'SUV',
    sellingPrice: '139999',
    type: 'Petrol',
    make: 'BMW',
    condition: 'new',
    color: 'Black',
    year: '2024',
    driveType: '4WD',
    model: 'G 550',
    fuelEfficiency: '14 MPG',
    door: '5',
    engineSize: '4.0L',
    cylinder: '8',
    vin: 'W1NYC8HJ0L0000007',
    offerType: 'Hot offer',
    listingDescription: 'The Mercedes-Benz G-Class is an icon of luxury and capability. Hand-built with a twin-turbo V8 and premium appointments throughout.',
    features: ['Sunroof', 'Leather Seats', 'Bluetooth', 'Backup Camera', 'Apple-CarPlay', 'Panoramic Moonroof', 'Heater'],
    images: ['https://content.carlelo.com/uploads/blog_img/1710568288.webp'],
    userId: 'system_seed',
    userEmail: 'seed@example.com',
    userName: 'System Seed',
  },
  {
    listingTitle: 'Porsche 911 Carrera',
    tagLine: 'Timeless sports car excellence',
    originalPrice: '120000',
    category: 'Coupe',
    sellingPrice: '114999',
    type: 'Petrol',
    make: 'Audi',
    condition: 'new',
    color: 'Blue',
    year: '2024',
    driveType: 'RWD',
    model: '911 Carrera',
    fuelEfficiency: '20 MPG',
    door: '2',
    engineSize: '3.0L',
    cylinder: '6',
    vin: 'WP0AA2A90LS000008',
    offerType: 'Buy',
    listingDescription: 'The Porsche 911 Carrera continues the legacy of the world\'s most iconic sports car. Precision engineering meets everyday usability.',
    features: ['Sunroof', 'Leather Seats', 'Bluetooth', 'Backup Camera', 'Digital Odometer', 'Power Steering'],
    images: ['https://content.carlelo.com/uploads/blog_img/1710568288.webp'],
    userId: 'system_seed',
    userEmail: 'seed@example.com',
    userName: 'System Seed',
  },
];

async function seed() {
  console.log('Seeding database with sample car listings...');
  try {
    for (const car of sampleCars) {
      await db.insert(CarListing).values(car);
      console.log(`Added: ${car.listingTitle}`);
    }
    console.log('Seed completed successfully!');
  } catch (error) {
    console.error('Error seeding database:', error);
  }
}

seed();

