import { serial, pgTable, varchar, integer, json, timestamp } from "drizzle-orm/pg-core";

export const CarListing = pgTable('carListing', {
    id: serial('id').primaryKey(),
    listingTitle: varchar('listing_title').notNull(),
    tagLine: varchar('tag_line'),
    originalPrice: varchar('original_price'),
    category: varchar('category'),
    sellingPrice: varchar('selling_price'),
    type: varchar('type'),
    make: varchar('make'),
    condition: varchar('condition'),
    color: varchar('color'),
    year: varchar('year'),
    driveType: varchar('drive_type'),
    model: varchar('model'),
    fuelEfficiency: varchar('fuel_efficiency'),
    door: varchar('door'),
    engineSize: varchar('engine_size'),
    cylinder: varchar('cylinder'),
    vin: varchar('vin'),
    offerType: varchar('offer_type'),
    listingDescription: varchar('listing_description'),
    features: json('features').default([]),
    images: json('images').default([]),
    userId: varchar('user_id').notNull(),
    userEmail: varchar('user_email'),
    userName: varchar('user_name'),
    createdAt: timestamp('created_at').defaultNow(),
});
